- name: openconfig-platform
  docs:
    - yang/platform/openconfig-platform.yang
    - yang/platform/openconfig-platform-types.yang
    - yang/platform/openconfig-platform-transceiver.yang
    - yang/platform/openconfig-platform-linecard.yang
    - yang/platform/openconfig-platform-port.yang
    - yang/platform/openconfig-platform-psu.yang
    - yang/platform/openconfig-platform-fan.yang
    - yang/platform/openconfig-platform-cpu.yang
    - yang/platform/openconfig-platform-ext.yang
  build:
    - yang/platform/openconfig-platform.yang
    - yang/platform/openconfig-platform-transceiver.yang
    - yang/platform/openconfig-platform-linecard.yang
    - yang/platform/openconfig-platform-port.yang
    - yang/platform/openconfig-platform-psu.yang
    - yang/platform/openconfig-platform-fan.yang
    - yang/platform/openconfig-platform-ext.yang
    - yang/platform/openconfig-platform-cpu.yang
  run-ci: true
