- name: openconfig-system
  docs:
    - yang/system/openconfig-aaa-types.yang
    - yang/system/openconfig-alarm-types.yang
    - yang/system/openconfig-system.yang
    - yang/system/openconfig-system-terminal.yang
    - yang/system/openconfig-system-logging.yang
    - yang/system/openconfig-procmon.yang
    - yang/system/openconfig-aaa.yang
    - yang/system/openconfig-aaa-tacacs.yang
    - yang/system/openconfig-aaa-radius.yang
    - yang/system/openconfig-alarms.yang
  build:
    - yang/system/openconfig-system.yang
  run-ci: true