- name: openconfig-network-instance
  docs:
    - yang/network-instance/openconfig-network-instance-types.yang
    - yang/network-instance/openconfig-network-instance.yang
  build:
    - yang/network-instance/openconfig-network-instance.yang
  run-ci: true